### ISSUE TITLE
Create a new IDataPack interface

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/james#10]
This new interface `IDataPack` will represent any kind of data package.
The first implementation will for XML using a new `TXmlPack` class.

The methods and its usage may be like this:
```pascal
var
  Doc: IXMLDocument;
begin
  Doc :=
    TXMLDocument.Create(
      TXMLPack.New
        .Add('root')
          .Add('items')
            .Add('item')
              .Add('code', 1).Up
              .Add('description', 'foo').Up
        .Root
        .Stream
    );
  Doc.SaveTo('file.xml');
end;
```

**Comment by heliosroots** [comment]
How would signature for IDataPack?

**Comment by mdbs99** [comment]
Initially, we will need a `Stream` method that returns a `DataStream`. That is the result.
This entity represents a data pack, but could be any format (XML, JSON, INI, etc). Thus, we will have a class for each one.
Then, I'm thinking to use some other methods to manipulate data like the example above. But these methods needs to be more generic as possible to work in all formats.
This project [here](https://github.com/yegor256/xembly) could be an inspiration.

**Comment by mdbs99** [comment]
This issue will be fix using my new project called Xavier.
Follow this https://github.com/mdbs99/james/issues/65#issuecomment-330058296 for more info.
