### ISSUE TITLE
Create a package test for Delphi

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/james#50]
There is no package test for Delphi yet.
Let's create `james.tests.dpk`.

**Comment by mdbs99** [comment]
@nunopicado could you handle it?

**Comment by nunopicado** [comment]
Yes, I'll take care of it.

**Comment by mdbs99** [comment]
Waiting many changes in `master` to merge with `delphi`, which has the project file to Delphi.

**Comment by nunopicado** [comment]
I can create it again over the new updates to master.
Since the test units are already compatible, it's less troublesome than to try and merge it.
However, do you think maybe we shoud try to address #65 before, so we could merge without pending issues related to compatibility?

**Comment by mdbs99** [comment]
Yes, let's try #65 first.
Indeed, I'm thinking about this issue days ago.
What do you think about #10?

**Comment by mdbs99** [comment]
Yes, let's try #65 first.
Indeed, I'm thinking about this issue days ago.
So, I will close this issue for now. We can create a new one at the future.
