### ISSUE TITLE
DUnit compatible

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/james#53]
Let's rename all `AssertXxx` methods to `CheckXxx` in all FPCUnit test classes to make compatible with DUnit.

**Comment by mdbs99** [comment]
@nunopicado please, check if it is compatible now.

**Comment by nunopicado** [comment]
It's one good step towards it, yes. Thank you.
You can close #53.

**Comment by mdbs99** [comment]
Ok, thanks.
