### ISSUE TITLE
James Testing unit

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/james#57]
Let's create a new unit to do the cross compile between FPC/Lazarus and Delphi.
We should encapsulate units that are used and test registrations.
Please, see this https://github.com/mdbs99/james/pull/56#discussion_r127968873 for more information.

**Comment by mdbs99** [comment]
This issue is awaiting resolution of this https://github.com/mdbs99/james/pull/62#discussion_r128682252

**Comment by mdbs99** [comment]
@nunopicado let's think how to resolve the generic syntax issue.
Why not a simple composition like below?
```pascal
  TTest = class sealed(TInterfacedObject, ITest)
  private
    FTestCase: TTestCase;
  public
    constructor Create(TestCase: TTestCase);
    class function New(TestCase: TTestCase): ITest;
    destructor Destroy; override;
    function RegisterOn(const SuitePath: string): ITest;
  end;

implementation

{ TTest }

constructor TTest.Create(TestCase: TTestCase);
begin
  inherited Create;
  FTestCase := TestCase
end;

class function TTest.New((TestCase: TTestCase)): ITest;
begin
  Result := Create(TestCase);
end;

// fpc ---------------
function TTest.RegisterOn(const SuitePath: string): ITest;
begin
  Result := Self;
  TestRegistry.RegisterTest(SuitePath, FTestCase);
end;

// delphi ---------------
function TTest.RegisterOn(const SuitePath: string): ITest;
begin
  Result := Self;
  TestFramework.RegisterTest(SuitePath, FTestCase.Suite);
end;
```

If you allow me to change your original idea, I can code this.
What you say?

**Comment by nunopicado** [comment]
Please, do try. I will not be able to work on this today, so if you can, we can advance this issue.

**Comment by mdbs99** [comment]
Done.
