### ISSUE TITLE
Directive {$include james.inc}

### ISSUE THREAD

**Issue by cleojunior** [mdbs99/james#66]
Let's change the directive from {$include james.inc} to {$include ..\inc\james.inc} because the james.inc file is in another directory.

**Comment by mdbs99** [comment]
In Lazarus we use include paths, passing some paths to compiler know where is the files. Delphi has the same.

Please, take a look in `delphi` branch. There is a Delphi project, which is the first cross compile (thanks @nunopicado for that), specifically in this line [here](https://github.com/mdbs99/james/blob/69f27b2973a333270134e7948d8c748f45d7c102/pkg/james.dproj#L132), to see this parameter.

If no question, please close the issue.
