### ISSUE TITLE
Only one Add() in TDataParams

### ISSUE THREAD

**Issue by fabriciofx** [mdbs99/james#85]
Nowadays, `IDataParams` has 3 `Add()` methods:
```
function Add(const ParamName: string; DataType: TFieldType; Value: Variant): IDataParams; overload;
function Add(const AParam: IDataParam): IDataParams; overload;
function Add(const AParams: IDataParams): IDataParams; overload;
```
So, my suggestion is to have only one `Add()` method, like this:
```
function Add(const AParam: IDataParam): IDataParams; overload;
```
When we want to save to a file, we can do something like it:
```
IDataParams ds = TDataParams.New();
ds.Add(TDataParam.New(...));
```
And, to allow add a `IDataParams` to a `IDataParams`, `IDataParams` show extends `IDataParam`.

WDYT?

**Comment by mdbs99** [comment]
I've just removed the first one. The last, I cannot, because the algorithm should need to execute a loop in all items.
